spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${MONGO_URI}   # <-- use env var instead of hardcoded localhost
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}   # <-- use env var
