package com.orderservice.system.categories;

import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class CategoryService {
    private final CategoryRepository categoryRepository;
    private final CategoryMapper mapper;

    public CategoryResponseDto addCategory(String name) {
        var entity = new CategoryEntity(null, name); // id will be generated by MongoDB
        var saved = categoryRepository.save(entity);
        return mapper.toResponse(saved);
    }

    // ✅ Get all categories
    public List<CategoryResponseDto> getAllCategories() {
        return categoryRepository.findAll()
                .stream()
                .map(mapper::toResponse)
                .toList();
    }

    // ✅ Get category by ID
    public CategoryResponseDto getCategoryById(String id) {
        var entity = categoryRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Category not found"));
        return mapper.toResponse(entity);
    }

    // ✅ Update category
    public CategoryResponseDto updateCategory(String id, CategoryRequestDto requestDto) {
        var entity = categoryRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Category not found"));
        entity.setName(requestDto.getName());
        // add other fields if needed
        var updated = categoryRepository.save(entity);
        return mapper.toResponse(updated);
    }

    // ✅ Delete category
    public void deleteCategory(String id) {
        if (!categoryRepository.existsById(id)) {
            throw new IllegalArgumentException("Category not found");
        }
        categoryRepository.deleteById(id);
    }

    @Bean
    CommandLineRunner seedCategories(CategoryRepository categoryRepository) {
        return args -> {
            if (categoryRepository.count() == 0) {
                categoryRepository.saveAll(List.of(
                        new CategoryEntity(null, "Hot Drinks & Snacks"),
                        new CategoryEntity(null, "Soft Drinks"),
                        new CategoryEntity(null, "Main Dishes"),
                        new CategoryEntity(null, "Beef (Nyama)"),
                        new CategoryEntity(null, "Mutton / Mbuzi"),
                        new CategoryEntity(null, "Kichwa (Mbuzi)"),
                        new CategoryEntity(null, "Orders")
                ));
                System.out.println("✅ Categories seeded successfully");
            } else {
                System.out.println("ℹ️ Categories already exist, skipping seeding");
            }
        };
    }
}



